name: kfs_user
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.0
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  razorpay_flutter: ^1.3.4
  simple_animations: ^5.0.0+3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  generate: true

